"""Add watering demand to profiles

Revision ID: 4081529515a0
Revises: e49b8b4a7b12
Create Date: 2026-08-14 19:20:56.903609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4081529515a0'
down_revision: Union[str, Sequence[str], None] = 'e49b8b4a7b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('watering_demand', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'watering_demand')
    # ### end Alembic commands ###
