"""Create add selected_at to profile

Revision ID: 4ddbd6ec024e
Revises: 2fcc72ade41c
Create Date: 2026-08-13 23:36:47.009737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddbd6ec024e'
down_revision: Union[str, Sequence[str], None] = '2fcc72ade41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('selected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'selected_at')
    # ### end Alembic commands ###
