"""Add profile seed entry

Revision ID: b95c7896cebb
Revises: 4ddbd6ec024e
Create Date: 2026-08-14 00:08:36.615967

"""
import uuid
from datetime import datetime
from typing import Sequence, Union

from alembic import op
from sqlalchemy import DateTime, table, column, Uuid, String

# revision identifiers, used by Alembic.
revision: str = 'b95c7896cebb'
down_revision: Union[str, Sequence[str], None] = '4ddbd6ec024e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(table("profile", column("id", Uuid), column("name", String), column("city", String),
                         column("selected_at", DateTime)), [
                       {
                           "id": uuid.uuid4(),
                           "name": "Default",
                           "city": "Berlin",
                           "selected_at": datetime.utcnow()
                       }
                   ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
