"""Add WaterTickEvent

Revision ID: e49b8b4a7b12
Revises: 88d1b76b4f68
Create Date: 2026-08-14 12:06:03.217396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49b8b4a7b12'
down_revision: Union[str, Sequence[str], None] = '88d1b76b4f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_tick_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('valve_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_tick_event')
    # ### end Alembic commands ###
